### ISSUE TITLE
Joining a Discord channel

### ISSUE THREAD

**Issue by Moosems** [leycec/leycec#2]
I am creating a development channel on Discord and thought I'd ask if you are interested. I'd love to collaborate with you on things like BearType but its hard with the delay you get when working through solely GH issues. If you don't want to, just let me know and there's no harm in it. Hope you're having a good day my dude!

**Comment by leycec** [comment]
**Sounds super-fun!** But... I am introverted autism personified. Real-time *anything* gets my hairy palms sweaty in a disconcerting manner. But... I should do this anyway! Social communication with awesome human beings is an essential part of this whole "Human" thing I keep hearing so many rumours about. You are awesome and presumably human. Therefore, the jigsaw puzzle pieces all fit.

I'm here for this whole "Human" thing. Oh, who am I kidding. It's mostly anime, video games, and Python in this man-cave. You can tell by the 80's posters plastered over the walls. Still, I should try to do this. Humanity deserves my attention! And... let's see if I do this. :sweat_smile:

**Comment by Moosems** [comment]
Don't worry, no one's gonna force you to respond in real time 😄

**Comment by Moosems** [comment]
Again, if you don't want to join, just let me know. I'm bad at social cues though, so be blunt (I don't get easily offended in any case) :D

**Comment by leycec** [comment]
**Addendum:** this hard-hitting action item actually relates to an [old @beartype issue about Gitter](https://github.com/beartype/beartype/issues/50). Basically, I wondered whether anyone might want to open up a @beartype-adjacent [Gitter channel](https://gitter.im/). Gitter is *sorta* Discord but just for GitHub and GitLab repos and orgs. Because it's just for GitHub and GitLab, it integrates *really* nicely and cleanly with everything we take for granted here – like:

* Markdown. :partying_face: 
* LaTeX. :vomiting_face: 
* User and org pinging with the `@` prefix. :hand:
* Issue and commit referencing with the `#` prefix. :yawning_face: 

Fun stuff... *or is it!?!?* Nobody ever replied, so I just quietly closed that issue. This is why we can't have good social. I like to pretend that I'd feel more comfortable and at ease on Gitter than Discord. It'd be swell to get all the GitHub integrations that come bundled with Gitter. As a gamer, I also mostly associate Discord with voice chat, MMORPG guilds, and FPS clans. Those aren't bad things *per say* – but they're not really *my* things. But... maybe that's a bad association? Maybe I'm an aging millenial who has no idea what's culturally going on anymore?

Oh, what do I know! Let's just play offline single-player Japanese video games tonight. :joy:

> "Shin Megami Tensei V: Vengeance": *prepare to destroy apocalyptic Tokyo yet again.*

**Comment by Moosems** [comment]
Thats completely fair. Porcupine once had a separate discussion about having an official chat and after like a year we chose to move to Discord from the IRC server we were on. I don't ever use Discord for voice chats, I just like that I can get pings on the go from Discord on my phone and be able to respond quickly. Is the speed *truly* necessary? No. I could most certainly go for being more patient, but I also move faster than most and want to get things moving. Waiting a week for someone to give their thoughts on what direction my projects should go is painfully long and by that point I'll just make the decision myself. I find that its also nice for taking your time if you want and responding as needed. Some of my best friends and even my brother are super introverted so its nice to be able to ping them every so often and just let them take the time they need to respond while also letting them see the message and I know that the message didn't get lost in the endless email void that is GH sending me updates on my actions/workflows.

**Comment by Moosems** [comment]
The link should you choose to join: https://discord.gg/Pa9bjza4

**Comment by leycec** [comment]
> the IRC server

**So much childhood nostalgia.** IRC was *wonderful.* Then again, so were BBSs (bulletin board systems), America Online (AOL), and Gopher. Nobody even knows what any of this archaic terminology means anymore. Mostly, it means dial-up modem sounds that sound the infernal bowels of hell igniting your computer on fire. :laughing: 

> Some of my best friends and even my brother are super introverted...

We are legion. The ineluctable craving to just code all day is strong. Dare I take a break? Dare I not code a line? Dare I actually chat with humans? Actually, I'm reminded at this timely interval of that most infamous T.S. Eliot poem – ["The Love Song of J. Alfred Prufrock"](https://www.poetryfoundation.org/poetrymagazine/poems/44212/the-love-song-of-j-alfred-prufrock):

```
I grow old ... I grow old ...
I shall wear the bottoms of my trousers rolled.

Shall I part my hair behind?   Do I dare to eat a peach?
I shall wear white flannel trousers, and walk upon the beach.
I have heard the mermaids singing, each to each.

I do not think that they will sing to me.

I have seen them riding seaward on the waves
Combing the white hair of the waves blown back
When the wind blows the water white and black.
We have lingered in the chambers of the sea
By sea-girls wreathed with seaweed red and brown
Till human voices wake us, and we drown.
```

He had me up until the whole "and we drown" part. I'm down with getting old, wearing the bottom of my trousers rolled, and daring to eat peaches. But I draw the line at cavorting with watery tarts wearing seaweed.

> The link should you choose to join: https://discord.gg/Pa9bjza4

**Thanks so much.** Please ping and prod me when I inevitably play video games all night instead. The inertia of signing up for another web service makes me want to lie down on the floor. `</just_millenial_problems>`

**Comment by Moosems** [comment]
@leycec ping and prod ;)
